/*
 * torque-NG: Next Generation Resource Manager
 *
 * Copyright (c) 2026 Kenneth Nielson.
 * Portions Copyright (c) 1999-2000 Veridian Information Solutions, Inc.
 * Licensed under the OpenPBS v2.3 Software License.
 */

#pragma once

#include <functional>
#include <iostream>
#include <memory>
#include <unordered_map>
// #include "torque_messages.pb.h" // This is generated by protoc
#include "torque_ng.pb.h" // This is generated by protoc

/**
 * @class MessageDispatcher
 * @brief Routes incoming Protobuf TorqueRequests to registered C++ handlers.
 * * This implements the "Inversion of Control" (IoC) pattern, allowing the
 * network layer to remain agnostic of the actual command logic.
 */
class MessageDispatcher {
public:
  // Define functional signatures for our handlers
  // These return a TorqueReply to be sent back across the wire
  using DeleteHandler = std::function<torque_ng::TorqueReply(
      const torque_ng::JobDeleteRequest &)>;
  using SubmitHandler = std::function<torque_ng::TorqueReply(
      const torque_ng::JobSubmitRequest &)>;
  using ObituaryHandler =
      std::function<torque_ng::TorqueReply(const torque_ng::JobObituary &)>;
  using StatusHandler = std::function<torque_ng::TorqueReply(
      const torque_ng::JobStatusRequest &)>;

  // Registration Methods
  void registerDeleteHandler(DeleteHandler h) {
    handlers_delete = std::move(h);
  }
  void registerSubmitHandler(SubmitHandler h) {
    handlers_submit = std::move(h);
  }
  void registerObituaryHandler(ObituaryHandler h) {
    handlers_obituary = std::move(h);
  }
  void registerStatusHandler(StatusHandler h) {
    handlers_status = std::move(h);
  }

  /**
   * @brief The main routing engine.
   * Uses the Protobuf 'oneof' case to jump to the correct logic.
   */
  torque_ng::TorqueReply route(const torque_ng::TorqueRequest &request) {
    switch (request.payload_case()) {

    case torque_ng::TorqueRequest::kDelete:
      if (handlers_delete)
        return handlers_delete(request.delete_());
      return createErrorReply("Delete handler not registered");

    case torque_ng::TorqueRequest::kSubmit:
      if (handlers_submit)
        return handlers_submit(request.submit());
      return createErrorReply("Submit handler not registered");

    case torque_ng::TorqueRequest::kObituary:
      if (handlers_obituary)
        return handlers_obituary(request.obituary());
      return createErrorReply("Obituary handler not registered");

    case torque_ng::TorqueRequest::PAYLOAD_NOT_SET:
      return createErrorReply("Empty request payload received");

    case torque_ng::TorqueRequest::kStatus:
      if (handlers_status)
        return handlers_status(request.status());
      return createErrorReply("Status handler not registered");

    default:
      return createErrorReply(
          "Command recognized in .proto but not yet implemented in Dispatcher");
    }
  }

private:
  // Storage for the registered lambdas/functions
  DeleteHandler handlers_delete;
  SubmitHandler handlers_submit;
  ObituaryHandler handlers_obituary;
  StatusHandler handlers_status;

  // Helper to generate a standardized error reply
  torque_ng::TorqueReply createErrorReply(const std::string &msg) {
    torque_ng::TorqueReply reply;
    reply.set_error_code(-1); // General Error
    reply.set_error_message(msg);
    return reply;
  }
};
