/*
*         OpenPBS (Portable Batch System) v2.3 Software License
*
* Copyright (c) 1999-2000 Veridian Information Solutions, Inc.
* All rights reserved.
*
* ---------------------------------------------------------------------------
* For a license to use or redistribute the OpenPBS software under conditions
* other than those described below, or to purchase support for this software,
* please contact Veridian Systems, PBS Products Department ("Licensor") at:
*
*    www.OpenPBS.org  +1 650 967-4675                  sales@OpenPBS.org
*                        877 902-4PBS (US toll-free)
* ---------------------------------------------------------------------------
*
* This license covers use of the OpenPBS v2.3 software (the "Software") at
* your site or location, and, for certain users, redistribution of the
* Software to other sites and locations.  Use and redistribution of
* OpenPBS v2.3 in source and binary forms, with or without modification,
* are permitted provided that all of the following conditions are met.
* After December 31, 2001, only conditions 3-6 must be met:
*
* 1. Commercial and/or non-commercial use of the Software is permitted
*    provided a current software registration is on file at www.OpenPBS.org.
*    If use of this software contributes to a publication, product, or
*    service, proper attribution must be given; see www.OpenPBS.org/credit.html
*
* 2. Redistribution in any form is only permitted for non-commercial,
*    non-profit purposes.  There can be no charge for the Software or any
*    software incorporating the Software.  Further, there can be no
*    expectation of revenue generated as a consequence of redistributing
*    the Software.
*
* 3. Any Redistribution of source code must retain the above copyright notice
*    and the acknowledgment contained in paragraph 6, this list of conditions
*    and the disclaimer contained in paragraph 7.
*
* 4. Any Redistribution in binary form must reproduce the above copyright
*    notice and the acknowledgment contained in paragraph 6, this list of
*    conditions and the disclaimer contained in paragraph 7 in the
*    documentation and/or other materials provided with the distribution.
*
* 5. Redistributions in any form must be accompanied by information on how to
*    obtain complete source code for the OpenPBS software and any
*    modifications and/or additions to the OpenPBS software.  The source code
*    must either be included in the distribution or be available for no more
*    than the cost of distribution plus a nominal fee, and all modifications
*    and additions to the Software must be freely redistributable by any party
*    (including Licensor) without restriction.
*
* 6. All advertising materials mentioning features or use of the Software must
*    display the following acknowledgment:
*
*     "This product includes software developed by NASA Ames Research Center,
*     Lawrence Livermore National Laboratory, and Veridian Information
*     Solutions, Inc.
*     Visit www.OpenPBS.org for OpenPBS software support,
*     products, and information."
*
* 7. DISCLAIMER OF WARRANTY
*
* THIS SOFTWARE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND. ANY EXPRESS
* OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
* OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT
* ARE EXPRESSLY DISCLAIMED.
*
* IN NO EVENT SHALL VERIDIAN CORPORATION, ITS AFFILIATED COMPANIES, OR THE
* U.S. GOVERNMENT OR ANY OF ITS AGENCIES BE LIABLE FOR ANY DIRECT OR INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
* LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
* OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
* LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
* NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
* This license will be governed by the laws of the Commonwealth of Virginia,
* without reference to its choice of law rules.
*/

#include <pbs_config.h>   /* the master config generated by configure */
#include <sys/types.h>
#include <sys/stat.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <limits.h>
#include "portability.h"
//#include "log.h"
#include "pbs_log.h"
#include <pwd.h>
#include <grp.h>
#include <unistd.h>
#include <string.h>

#include <iostream>
#include <filesystem>
#include <string_view>
#include <string>
#include <system_error>

namespace fs = std::filesystem;

#ifndef S_ISLNK
#define S_ISLNK(m) (((m) & S_IFMT) == S_IFLNK)
#endif

int chk_file_sec_stderr = 0;
// Defining security policy constants
constexpr uid_t MAX_ADMIN_UID = 10;
constexpr gid_t MAX_ADMIN_GID = 9;

/**
 * @brief Verifies if the process has full root privileges.
 * * Checks both the Real User ID (getuid) and Effective User ID (geteuid) 
 * to ensure the process is not just temporarily elevated but truly 
 * running as the superuser. Logs a failure to stderr and the system log.
 * * @return true if both UIDs are 0, false otherwise.
 */
bool IamRoot()
{
	if ((getuid() == 0) && (geteuid() == 0))
		return true;

  std::cerr << "Must be run as root" << std::endl;

  log_err(-1, __func__, "Must be run as root");
	return false;
}

/**
 * @brief Centralizes security violation reporting and logging.
 * * Constructs a detailed error message using the provided path and 
 * violation description. Depending on the global configuration, 
 * outputs the error to stdout or the internal PBS logging system.
 * * @param rc The error code associated with the violation (usually an errno).
 * @param path The fs::path where the violation occurred.
 * @param SEMsg [in, out] Inbound specific violation message; outbound fully formatted error string.
 */
void report_security_error(
  int rc, 
  const fs::path& path, 
  std::string& SEMsg)
{
  std::ostringstream oss;

  // If a specific error message was already set during the checks
  if (!SEMsg.empty())
    {
    oss << "Security violation with \"" << path.string() << "\" - " << SEMsg;
    }
  else
    {
    // Fallback for general system errors (like stat failure)
    oss << "Security violation with \"" << path.string() << "\", errno=" << rc 
        << ", " << strerror(rc);
    }

  // Update the output reference
  SEMsg = oss.str();

  // Handle logging based on the global flag
  if (chk_file_sec_stderr)
    {
    std::cout << "chk_tree: " << SEMsg << " (error #" << rc << ")" << std::endl;
    }
  else
    {
    // Uses the thread-safe logging you refactored in pbs_log.cpp
    log_err(rc, "chk_file_sec", SEMsg.c_str());
    }
}

 /**
 * @brief Evaluates file or directory security according to PBS safety policies.
 * * Part of the HPC resource management security layer. This function ensures that
 * a path is protected from unauthorized modification by verifying the ownership
 * and permission chain from the root down to the target.
 *
 * @details Security Criteria:
 * - Ownership: All path components must be owned by an administrative UID (UID < 10).
 * - Group Write: If group-writable, the GID must be an administrative GID (GID < 10).
 * - World Write: World-writable paths are rejected unless the sticky bit is set 
 * and explicitly allowed by the caller (typically for spool/temp directories).
 *
 * @param path The filesystem path to validate.
 * @param isdir True if the target is expected to be a directory, false for a regular file.
 * @param sticky If true, allows world-write access if the sticky bit is present.
 * @param disallow Bitmask of permission bits (S_IWGRP, S_IWOTH, etc.) to explicitly forbid.
 * @param check_full_path If true, recursively validates every parent directory up to the root.
 * @param SEMsg [out] String reference populated with a detailed description of any security violation.
 * * @return 0 on success.
 * @return Non-zero system errno on failure:
 * - EPERM:   Ownership violation (non-admin owner).
 * - ENOTDIR: File type mismatch.
 * - EACCES:  Permission bit violation (e.g., world-writable).
 * - ENOENT:  Path does not exist.
 */

 int chk_file_sec(
  const fs::path& path,
  bool   isdir,
  bool   sticky,
  int    disallow,
  bool   check_full_path,
  std::string& SEMsg)
{
  int rc = 0;

  // 1. Recursive Parent Path Check
  if (path.is_absolute() && check_full_path)
  {
    if (path.has_parent_path() && path.parent_path() != path.root_path())
    {
      rc = chk_file_sec(path.parent_path(), true, sticky, S_IWGRP | S_IWOTH, true, SEMsg);
      if (rc != 0) return rc;
    }
  }

  // 2. Get Modern Status
  std::error_code ec;
  auto sbuf = fs::symlink_status(path, ec);
  if (ec) {
    SEMsg = " cannot stat " + path.string() + ": " + ec.message();
    report_security_error(ec.value(), path, SEMsg);
    return ec.value();
  }
    
  // 3. Symlink Handling
  if (fs::is_symlink(sbuf))
  {
    fs::path target = fs::read_symlink(path, ec);
    if (ec)
    {
      SEMsg = "cannot be read as link: " + ec.message();
      report_security_error(ec.value(), path, SEMsg);
      return ec.value();
    }

    fs::path next_path = target.is_absolute() ? target : (path.parent_path() / target);
    return chk_file_sec(next_path, isdir, sticky, disallow, check_full_path, SEMsg);
  }

  // 4. Get Legacy Status (for UID/GID)
  struct stat st;
  if (lstat(path.c_str(), &st) != 0)
  {
    rc = errno;
    SEMsg = " cannot lstat " + path.string() + ": " + strerror(rc);
    report_security_error(rc, path, SEMsg);
    return rc;
  }
    
  // 5. Admin Ownership Check
  if (st.st_uid > MAX_ADMIN_UID)
  {
    SEMsg = "is not owned by admin user";
    report_security_error(EPERM, path, SEMsg);
    return EPERM;
  }

  // 6. File Type Validation
  if (isdir)
  {
    if (!fs::is_directory(sbuf))
    {
      SEMsg = "is not a directory";
      report_security_error(ENOTDIR, path, SEMsg);
      return ENOTDIR;
    }
  }
  else if (!fs::is_regular_file(sbuf))
  {
    SEMsg = "is not a regular file";
    report_security_error(EBADF, path, SEMsg);
    return EBADF;
  }

  // 7. Sticky Bit and Permission Enforcement
  bool has_sticky = (st.st_mode & S_ISVTX) != 0;
  int current_mode = st.st_mode & 0777;

  if (isdir && sticky && !check_full_path)
  {
    if (!has_sticky || (current_mode != 0777))
    {
      SEMsg = "directory lacks sticky bit or 0777 permissions";
      report_security_error(EACCES, path, SEMsg);
      return EACCES;
    }
  }

  if ((current_mode & disallow) != 0)
  {
    if ((current_mode & disallow & S_IWGRP) && (st.st_gid > MAX_ADMIN_GID))
    {
      SEMsg = "is group writable by non-admin group";
      report_security_error(EPERM, path, SEMsg);
      return EPERM;
    }

    if (current_mode & disallow & S_IWOTH)
    {
      if (!fs::is_directory(sbuf) || !has_sticky || !sticky)
      {
        SEMsg = "is world writable and not sticky";
        report_security_error(EACCES, path, SEMsg);
        return EACCES;
      }
    }

    if (current_mode & disallow & ~(S_IWGRP | S_IWOTH))
    {
      SEMsg = "has prohibited permission bits set";
      report_security_error(EACCES, path, SEMsg);
      return EACCES;
    }
  }

  return 0; 
}
/* END chk_file_sec.c */
